### ISSUE TITLE
Suggest Ant for alternative to org.gradle.internal.os.OperatingSystem?

### ISSUE THREAD

**Issue by rhencke** [gradle-guides/designing-gradle-plugins#12]
In the document Authoring Maintainable Build Scripts, under [Alternatives for oft-used internal APIs](https://docs.gradle.org/current/userguide/authoring_maintainable_build_scripts.html#alternatives_for_oft_used_internal_apis), there is a passage that reads:

> Instead of `org.gradle.internal.os.OperatingSystem`, use another method to detect operating system, such as Apache commons-lang SystemUtils or `System.getProperty("os.name")`.

There is another alternative I think is worth mentioning here - Ant's [`Os.isFamily`](https://ant.apache.org/manual/api/org/apache/tools/ant/taskdefs/condition/Os.html#isFamily-java.lang.String-) method.  Since Ant is included with Gradle, it has the advantage of not bringing in any extra dependencies.  It also takes care of all the variations you might see in `System.getProperty("os.name")` automatically, so no string wizardry is needed.

I'd be happy to submit a PR adding this option, but wanted to get thoughts first about if this change was agreed with.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #260](https://github.com/gradle/guides/issues/260) via [**ZenHub**](https://www.zenhub.com/)
