### ISSUE TITLE
Write section of use of software model for plugin development

### ISSUE THREAD

**Issue by bmuschko** [gradle-guides/designing-gradle-plugins#6]
Happy to collaborate on this. We should put this together as soon as we are ready for communicating it.

**Comment by eriwen** [comment]
Seems like we oughta close this. Agreed @bmuschko @lacasseio?

**Comment by bmuschko** [comment]
This is still needed. Plugin user will need to be made aware that they should _not_ write plugins with the software model. Example: https://github.com/gradle/gradle/issues/4327

**Comment by lacasseio** [comment]
Closing, the message is somewhat clear enough.
